LEVEL=..
LIBRARYNAME = libstabilizer
LOADABLE_MODULE = 1
USEDLIBS = 

include $(LEVEL)/Makefile.common

CPPFLAGS += -DNDEBUG -I. -I./diehard -I./diehard/diehard -D_REENTRANT=0 -DHL_EXECUTABLE_HEAP -DHL_32BIT_HEAP -msse3
