LEVEL = ../..

LIBRARYNAME = libstabilizer
LOADABLE_MODULE = 1

#LIBRARYNAME = stabilizer
#BUILD_ARCHIVE = 1

include $(LEVEL)/Makefile.common

CPPFLAGS += --std=c++0x -DNDEBUG -I. -fexceptions \
	-I hl \
	-I dh/src/include \
	-I dh/src/include/rng \
	-I dh/src/include/math \
	-I dh/src/include/util \
	-I dh/src/include/layers \
	-I dh/src/include/static

