ROOT = ..

TARGETS = $(ROOT)/libLLVMStabilizer.$(SHLIB_SUFFIX)
LIBS = 

include $(ROOT)/common.mk

CXXFLAGS += -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-exceptions -fno-rtti -fno-common
